name: Build Resume LaTeX Document
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Compile Resume LaTeX document
        uses: Sakul6499/GitHub-Action-LaTeX@v1.0.0
        with:
          latex_main_file: resume.tex

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: resume.pdf
          path: ./
        if: always()
